//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace myFormBuilder.Model.FolderService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FolderServiceSoap", Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FolderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private User userField;
        
        private System.Threading.SendOrPostCallback GetContentRootFolderIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditFolderNodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteLocationFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadFolderAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveFolderAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFolderAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveFolderElementOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveFolderElementOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFolderElementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FolderService() {
            this.Url = global::myFormBuilder.Model.Properties.Settings.Default.myFormBuilder_Model_FolderService_FolderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetContentRootFolderIdCompletedEventHandler GetContentRootFolderIdCompleted;
        
        /// <remarks/>
        public event EditFolderNodeCompletedEventHandler EditFolderNodeCompleted;
        
        /// <remarks/>
        public event LoadFolderCompletedEventHandler LoadFolderCompleted;
        
        /// <remarks/>
        public event SaveFolderCompletedEventHandler SaveFolderCompleted;
        
        /// <remarks/>
        public event DeleteFolderCompletedEventHandler DeleteFolderCompleted;
        
        /// <remarks/>
        public event DeleteLocationFolderCompletedEventHandler DeleteLocationFolderCompleted;
        
        /// <remarks/>
        public event CreateNewFolderCompletedEventHandler CreateNewFolderCompleted;
        
        /// <remarks/>
        public event LoadFolderAttributesCompletedEventHandler LoadFolderAttributesCompleted;
        
        /// <remarks/>
        public event SaveFolderAttributeCompletedEventHandler SaveFolderAttributeCompleted;
        
        /// <remarks/>
        public event DeleteFolderAttributeCompletedEventHandler DeleteFolderAttributeCompleted;
        
        /// <remarks/>
        public event SaveFolderElementCompletedEventHandler SaveFolderElementCompleted;
        
        /// <remarks/>
        public event MoveFolderElementCompletedEventHandler MoveFolderElementCompleted;
        
        /// <remarks/>
        public event DeleteFolderElementCompletedEventHandler DeleteFolderElementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/GetContentRootFolderId", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetContentRootFolderId() {
            object[] results = this.Invoke("GetContentRootFolderId", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetContentRootFolderIdAsync() {
            this.GetContentRootFolderIdAsync(null);
        }
        
        /// <remarks/>
        public void GetContentRootFolderIdAsync(object userState) {
            if ((this.GetContentRootFolderIdOperationCompleted == null)) {
                this.GetContentRootFolderIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContentRootFolderIdOperationCompleted);
            }
            this.InvokeAsync("GetContentRootFolderId", new object[0], this.GetContentRootFolderIdOperationCompleted, userState);
        }
        
        private void OnGetContentRootFolderIdOperationCompleted(object arg) {
            if ((this.GetContentRootFolderIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContentRootFolderIdCompleted(this, new GetContentRootFolderIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/EditFolderNode", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EditFolderNode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Folder folder) {
            object[] results = this.Invoke("EditFolderNode", new object[] {
                        folder});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EditFolderNodeAsync(Folder folder) {
            this.EditFolderNodeAsync(folder, null);
        }
        
        /// <remarks/>
        public void EditFolderNodeAsync(Folder folder, object userState) {
            if ((this.EditFolderNodeOperationCompleted == null)) {
                this.EditFolderNodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditFolderNodeOperationCompleted);
            }
            this.InvokeAsync("EditFolderNode", new object[] {
                        folder}, this.EditFolderNodeOperationCompleted, userState);
        }
        
        private void OnEditFolderNodeOperationCompleted(object arg) {
            if ((this.EditFolderNodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditFolderNodeCompleted(this, new EditFolderNodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/LoadFolder", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("folder", IsNullable=true)]
        public Folder LoadFolder(string folderId) {
            object[] results = this.Invoke("LoadFolder", new object[] {
                        folderId});
            return ((Folder)(results[0]));
        }
        
        /// <remarks/>
        public void LoadFolderAsync(string folderId) {
            this.LoadFolderAsync(folderId, null);
        }
        
        /// <remarks/>
        public void LoadFolderAsync(string folderId, object userState) {
            if ((this.LoadFolderOperationCompleted == null)) {
                this.LoadFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadFolderOperationCompleted);
            }
            this.InvokeAsync("LoadFolder", new object[] {
                        folderId}, this.LoadFolderOperationCompleted, userState);
        }
        
        private void OnLoadFolderOperationCompleted(object arg) {
            if ((this.LoadFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadFolderCompleted(this, new LoadFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SaveFolder", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveFolder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Folder folder) {
            object[] results = this.Invoke("SaveFolder", new object[] {
                        folder});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveFolderAsync(Folder folder) {
            this.SaveFolderAsync(folder, null);
        }
        
        /// <remarks/>
        public void SaveFolderAsync(Folder folder, object userState) {
            if ((this.SaveFolderOperationCompleted == null)) {
                this.SaveFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveFolderOperationCompleted);
            }
            this.InvokeAsync("SaveFolder", new object[] {
                        folder}, this.SaveFolderOperationCompleted, userState);
        }
        
        private void OnSaveFolderOperationCompleted(object arg) {
            if ((this.SaveFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveFolderCompleted(this, new SaveFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteFolder", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFolder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Folder folder) {
            object[] results = this.Invoke("DeleteFolder", new object[] {
                        folder});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFolderAsync(Folder folder) {
            this.DeleteFolderAsync(folder, null);
        }
        
        /// <remarks/>
        public void DeleteFolderAsync(Folder folder, object userState) {
            if ((this.DeleteFolderOperationCompleted == null)) {
                this.DeleteFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFolderOperationCompleted);
            }
            this.InvokeAsync("DeleteFolder", new object[] {
                        folder}, this.DeleteFolderOperationCompleted, userState);
        }
        
        private void OnDeleteFolderOperationCompleted(object arg) {
            if ((this.DeleteFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFolderCompleted(this, new DeleteFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteLocationFolder", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteLocationFolder(string parentFolderId, string deleteFolderId) {
            object[] results = this.Invoke("DeleteLocationFolder", new object[] {
                        parentFolderId,
                        deleteFolderId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteLocationFolderAsync(string parentFolderId, string deleteFolderId) {
            this.DeleteLocationFolderAsync(parentFolderId, deleteFolderId, null);
        }
        
        /// <remarks/>
        public void DeleteLocationFolderAsync(string parentFolderId, string deleteFolderId, object userState) {
            if ((this.DeleteLocationFolderOperationCompleted == null)) {
                this.DeleteLocationFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteLocationFolderOperationCompleted);
            }
            this.InvokeAsync("DeleteLocationFolder", new object[] {
                        parentFolderId,
                        deleteFolderId}, this.DeleteLocationFolderOperationCompleted, userState);
        }
        
        private void OnDeleteLocationFolderOperationCompleted(object arg) {
            if ((this.DeleteLocationFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteLocationFolderCompleted(this, new DeleteLocationFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/CreateNewFolder", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("folder", IsNullable=true)]
        public Folder CreateNewFolder(FolderType folderType, string strFolderName, string strParentFolderUUID) {
            object[] results = this.Invoke("CreateNewFolder", new object[] {
                        folderType,
                        strFolderName,
                        strParentFolderUUID});
            return ((Folder)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewFolderAsync(FolderType folderType, string strFolderName, string strParentFolderUUID) {
            this.CreateNewFolderAsync(folderType, strFolderName, strParentFolderUUID, null);
        }
        
        /// <remarks/>
        public void CreateNewFolderAsync(FolderType folderType, string strFolderName, string strParentFolderUUID, object userState) {
            if ((this.CreateNewFolderOperationCompleted == null)) {
                this.CreateNewFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewFolderOperationCompleted);
            }
            this.InvokeAsync("CreateNewFolder", new object[] {
                        folderType,
                        strFolderName,
                        strParentFolderUUID}, this.CreateNewFolderOperationCompleted, userState);
        }
        
        private void OnCreateNewFolderOperationCompleted(object arg) {
            if ((this.CreateNewFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewFolderCompleted(this, new CreateNewFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/LoadFolderAttributes", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderAttribute[] LoadFolderAttributes(string folderId) {
            object[] results = this.Invoke("LoadFolderAttributes", new object[] {
                        folderId});
            return ((FolderAttribute[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadFolderAttributesAsync(string folderId) {
            this.LoadFolderAttributesAsync(folderId, null);
        }
        
        /// <remarks/>
        public void LoadFolderAttributesAsync(string folderId, object userState) {
            if ((this.LoadFolderAttributesOperationCompleted == null)) {
                this.LoadFolderAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadFolderAttributesOperationCompleted);
            }
            this.InvokeAsync("LoadFolderAttributes", new object[] {
                        folderId}, this.LoadFolderAttributesOperationCompleted, userState);
        }
        
        private void OnLoadFolderAttributesOperationCompleted(object arg) {
            if ((this.LoadFolderAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadFolderAttributesCompleted(this, new LoadFolderAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SaveFolderAttribute", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveFolderAttribute(FolderAttribute fa) {
            object[] results = this.Invoke("SaveFolderAttribute", new object[] {
                        fa});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveFolderAttributeAsync(FolderAttribute fa) {
            this.SaveFolderAttributeAsync(fa, null);
        }
        
        /// <remarks/>
        public void SaveFolderAttributeAsync(FolderAttribute fa, object userState) {
            if ((this.SaveFolderAttributeOperationCompleted == null)) {
                this.SaveFolderAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveFolderAttributeOperationCompleted);
            }
            this.InvokeAsync("SaveFolderAttribute", new object[] {
                        fa}, this.SaveFolderAttributeOperationCompleted, userState);
        }
        
        private void OnSaveFolderAttributeOperationCompleted(object arg) {
            if ((this.SaveFolderAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveFolderAttributeCompleted(this, new SaveFolderAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteFolderAttribute", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFolderAttribute(FolderAttribute fa) {
            object[] results = this.Invoke("DeleteFolderAttribute", new object[] {
                        fa});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFolderAttributeAsync(FolderAttribute fa) {
            this.DeleteFolderAttributeAsync(fa, null);
        }
        
        /// <remarks/>
        public void DeleteFolderAttributeAsync(FolderAttribute fa, object userState) {
            if ((this.DeleteFolderAttributeOperationCompleted == null)) {
                this.DeleteFolderAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFolderAttributeOperationCompleted);
            }
            this.InvokeAsync("DeleteFolderAttribute", new object[] {
                        fa}, this.DeleteFolderAttributeOperationCompleted, userState);
        }
        
        private void OnDeleteFolderAttributeOperationCompleted(object arg) {
            if ((this.DeleteFolderAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFolderAttributeCompleted(this, new DeleteFolderAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/SaveFolderElement", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveFolderElement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FolderElement FolderElement) {
            object[] results = this.Invoke("SaveFolderElement", new object[] {
                        FolderElement});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveFolderElementAsync(FolderElement FolderElement) {
            this.SaveFolderElementAsync(FolderElement, null);
        }
        
        /// <remarks/>
        public void SaveFolderElementAsync(FolderElement FolderElement, object userState) {
            if ((this.SaveFolderElementOperationCompleted == null)) {
                this.SaveFolderElementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveFolderElementOperationCompleted);
            }
            this.InvokeAsync("SaveFolderElement", new object[] {
                        FolderElement}, this.SaveFolderElementOperationCompleted, userState);
        }
        
        private void OnSaveFolderElementOperationCompleted(object arg) {
            if ((this.SaveFolderElementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveFolderElementCompleted(this, new SaveFolderElementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/MoveFolderElement", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderServiceResult MoveFolderElement(string sourceFolderId, string targetFolderId, string movingElementId) {
            object[] results = this.Invoke("MoveFolderElement", new object[] {
                        sourceFolderId,
                        targetFolderId,
                        movingElementId});
            return ((FolderServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void MoveFolderElementAsync(string sourceFolderId, string targetFolderId, string movingElementId) {
            this.MoveFolderElementAsync(sourceFolderId, targetFolderId, movingElementId, null);
        }
        
        /// <remarks/>
        public void MoveFolderElementAsync(string sourceFolderId, string targetFolderId, string movingElementId, object userState) {
            if ((this.MoveFolderElementOperationCompleted == null)) {
                this.MoveFolderElementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveFolderElementOperationCompleted);
            }
            this.InvokeAsync("MoveFolderElement", new object[] {
                        sourceFolderId,
                        targetFolderId,
                        movingElementId}, this.MoveFolderElementOperationCompleted, userState);
        }
        
        private void OnMoveFolderElementOperationCompleted(object arg) {
            if ((this.MoveFolderElementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveFolderElementCompleted(this, new MoveFolderElementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("user")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prometric.com/webservices/intelitest/DeleteFolderElement", RequestNamespace="http://www.prometric.com/webservices/intelitest", ResponseNamespace="http://www.prometric.com/webservices/intelitest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFolderElement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FolderElement FolderElement) {
            object[] results = this.Invoke("DeleteFolderElement", new object[] {
                        FolderElement});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFolderElementAsync(FolderElement FolderElement) {
            this.DeleteFolderElementAsync(FolderElement, null);
        }
        
        /// <remarks/>
        public void DeleteFolderElementAsync(FolderElement FolderElement, object userState) {
            if ((this.DeleteFolderElementOperationCompleted == null)) {
                this.DeleteFolderElementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFolderElementOperationCompleted);
            }
            this.InvokeAsync("DeleteFolderElement", new object[] {
                        FolderElement}, this.DeleteFolderElementOperationCompleted, userState);
        }
        
        private void OnDeleteFolderElementOperationCompleted(object arg) {
            if ((this.DeleteFolderElementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFolderElementCompleted(this, new DeleteFolderElementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    [System.Xml.Serialization.XmlRootAttribute("user", Namespace="http://www.prometric.com/webservices/intelitest", IsNullable=false)]
    public partial class User : System.Web.Services.Protocols.SoapHeader {
        
        private string currentContextIdField;
        
        private string userNameField;
        
        private string userIdField;
        
        private bool authenticatedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currentContextId {
            get {
                return this.currentContextIdField;
            }
            set {
                this.currentContextIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FolderServiceResult {
        
        private string statusMessageField;
        
        private bool successStatusField;
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool SuccessStatus {
            get {
                return this.successStatusField;
            }
            set {
                this.successStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FolderElement {
        
        private string folderElementIdField;
        
        private string folderIdField;
        
        private string referenceIdField;
        
        private string referenceTypeField;
        
        private string referenceNameField;
        
        private System.DateTime utcStartDatetimeField;
        
        private System.DateTime utcEndDatetimeField;
        
        private System.DateTime utcCreateDatetimeField;
        
        private string createUserField;
        
        private System.DateTime utcModifiedDatetimeField;
        
        private string modifiedUserField;
        
        /// <remarks/>
        public string FolderElementId {
            get {
                return this.folderElementIdField;
            }
            set {
                this.folderElementIdField = value;
            }
        }
        
        /// <remarks/>
        public string FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcStartDatetime {
            get {
                return this.utcStartDatetimeField;
            }
            set {
                this.utcStartDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcEndDatetime {
            get {
                return this.utcEndDatetimeField;
            }
            set {
                this.utcEndDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcCreateDatetime {
            get {
                return this.utcCreateDatetimeField;
            }
            set {
                this.utcCreateDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcModifiedDatetime {
            get {
                return this.utcModifiedDatetimeField;
            }
            set {
                this.utcModifiedDatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class FolderAttribute {
        
        private string folderAttributeIdField;
        
        private string folderIdField;
        
        private string attributeField;
        
        private string valueField;
        
        private string createUserField;
        
        private string modifiedUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolderAttributeId {
            get {
                return this.folderAttributeIdField;
            }
            set {
                this.folderAttributeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public partial class Folder {
        
        private string folderNameField;
        
        private string folderIdField;
        
        private string folderTypeIdField;
        
        private string folderTypeNameField;
        
        private bool isLockedField;
        
        private bool isHiddenField;
        
        private bool isSystemField;
        
        private System.DateTime utcCreateDateTimeField;
        
        private System.DateTime utcLockedDateTimeField;
        
        private System.DateTime utcModifiedDateTimeField;
        
        private string createUserField;
        
        private string modifiedUserField;
        
        /// <remarks/>
        public string FolderName {
            get {
                return this.folderNameField;
            }
            set {
                this.folderNameField = value;
            }
        }
        
        /// <remarks/>
        public string FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public string FolderTypeId {
            get {
                return this.folderTypeIdField;
            }
            set {
                this.folderTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string FolderTypeName {
            get {
                return this.folderTypeNameField;
            }
            set {
                this.folderTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHidden {
            get {
                return this.isHiddenField;
            }
            set {
                this.isHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSystem {
            get {
                return this.isSystemField;
            }
            set {
                this.isSystemField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcCreateDateTime {
            get {
                return this.utcCreateDateTimeField;
            }
            set {
                this.utcCreateDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcLockedDateTime {
            get {
                return this.utcLockedDateTimeField;
            }
            set {
                this.utcLockedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime utcModifiedDateTime {
            get {
                return this.utcModifiedDateTimeField;
            }
            set {
                this.utcModifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prometric.com/webservices/intelitest")]
    public enum FolderType {
        
        /// <remarks/>
        Folder,
        
        /// <remarks/>
        Roles,
        
        /// <remarks/>
        Users,
        
        /// <remarks/>
        Permissions,
        
        /// <remarks/>
        Workflows,
        
        /// <remarks/>
        ItemTypes,
        
        /// <remarks/>
        ICSNode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetContentRootFolderIdCompletedEventHandler(object sender, GetContentRootFolderIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContentRootFolderIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContentRootFolderIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EditFolderNodeCompletedEventHandler(object sender, EditFolderNodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditFolderNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditFolderNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoadFolderCompletedEventHandler(object sender, LoadFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Folder Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Folder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveFolderCompletedEventHandler(object sender, SaveFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteFolderCompletedEventHandler(object sender, DeleteFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteLocationFolderCompletedEventHandler(object sender, DeleteLocationFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteLocationFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteLocationFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateNewFolderCompletedEventHandler(object sender, CreateNewFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Folder Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Folder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoadFolderAttributesCompletedEventHandler(object sender, LoadFolderAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadFolderAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadFolderAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderAttribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderAttribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveFolderAttributeCompletedEventHandler(object sender, SaveFolderAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveFolderAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveFolderAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteFolderAttributeCompletedEventHandler(object sender, DeleteFolderAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFolderAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFolderAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveFolderElementCompletedEventHandler(object sender, SaveFolderElementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveFolderElementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveFolderElementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MoveFolderElementCompletedEventHandler(object sender, MoveFolderElementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveFolderElementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveFolderElementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteFolderElementCompletedEventHandler(object sender, DeleteFolderElementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFolderElementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFolderElementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591