//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFormBuilder.Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/Public/AutoGenCodeWe" +
            "bService.asmx")]
        public string myFormBuilder_Model_AutoGenCodeWebService_AutoGenCodeWebService {
            get {
                return ((string)(this["myFormBuilder_Model_AutoGenCodeWebService_AutoGenCodeWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/ExamService.asmx")]
        public string myFormBuilder_Model_ExamService_ExamService {
            get {
                return ((string)(this["myFormBuilder_Model_ExamService_ExamService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/FolderService.asmx")]
        public string myFormBuilder_Model_FolderService_FolderService {
            get {
                return ((string)(this["myFormBuilder_Model_FolderService_FolderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/ICSService.asmx")]
        public string myFormBuilder_Model_ICSService_ICSService {
            get {
                return ((string)(this["myFormBuilder_Model_ICSService_ICSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/ItemService.asmx")]
        public string myFormBuilder_Model_ItemService_ItemService {
            get {
                return ((string)(this["myFormBuilder_Model_ItemService_ItemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/ListService.asmx")]
        public string myFormBuilder_Model_ListService_ListService {
            get {
                return ((string)(this["myFormBuilder_Model_ListService_ListService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/SearchService.asmx")]
        public string myFormBuilder_Model_SearchService_SearchService {
            get {
                return ((string)(this["myFormBuilder_Model_SearchService_SearchService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bil-itest2-app.prometric.qc2/IntelitestWS/WebServices/SecurityService.asmx" +
            "")]
        public string myFormBuilder_Model_SecurityService_SecurityService {
            get {
                return ((string)(this["myFormBuilder_Model_SecurityService_SecurityService"]));
            }
        }
    }
}
